name: build and deploy mkdocs to github pages

on:
  push:
    branches:
      - master
      - github-action

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8.6'
          architecture: 'x64'

      # todo: move to action
      - name: Setup plantuml with deps
        run:  DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get -yq install plantuml graphviz make

    # commenting for now: use this if we start running tests via gh-actions!
    # for now, only mkdocs is required - no need to install/cache all requirements
    #  - name: Cache dependencies
    #    uses: actions/cache@v1
    #    with:
    #      path: ~/.cache/pip
    #      key: $-pip-$
    #      restore-keys: |
    #        $-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -U pipenv
          pipenv sync

      - name: Generate adr toc
        run: ./bin/adr generate toc > docs/architecture/index.md

      - name: Generate interactive view
        run: pipenv run adr-viewer --adr-path ./docs/architecture/decisions/ --output docs/architecture/decisions/decisions.html 

      - name: Patch adr toc
        run: sed -i 's/\.md"/\/index.html"/g' docs/architecture/decisions/decisions.html

      - name: Build site
        run: pipenv run mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          publish_dir: ./public
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages

